
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/steps/01-GA-Basics-solution"
    schedule:
      interval: daily
      time: "04:00"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 99
    rebase-strategy: "auto"
  - package-ecosystem: github-actions
    directory: "/steps/02-Interact-With-Env-solution"
    schedule:
      interval: daily
      time: "04:00"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 99
    rebase-strategy: "auto"
  - package-ecosystem: github-actions
    directory: "/steps/03-Reusable-Workflows-solution"
    schedule:
      interval: daily
      time: "04:00"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 99
    rebase-strategy: "auto"
  - package-ecosystem: github-actions
    directory: "/steps/05-Advanced-Concepts-solution"
    schedule:
      interval: daily
      time: "04:00"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 99
    rebase-strategy: "auto"
